routes/backend.php
<?php
/**
 * Created by PhpStorm.
 * User: naingminkhant
 * Date: 11/19/18
 * Time: 1:35 PM
 */

Route::get('/', 'DashboardController@index')->name('dashboard');

Route::group([
    'as' => 'backend.',
], function () {
    Route::resource('user', 'UserController');
    Route::resource('category', 'CategoryController');
    Route::resource('{category_id}/sub-category', 'SubCategoryController');

    Route::resource('director', 'DirectorController');
    Route::resource('cast', 'CastController');
    Route::resource('company', 'CompanyController');
    Route::resource('country', 'CountryController');

    /**
     * Individual Video
     */
    Route::post('video/{id}/delete', 'VideoController@destroyVideo')->name('destroy-video');
    Route::resource('video', 'VideoController');

    /**
     * Upload Video
     */
    Route::post('only-video/delete', 'VideoController@destroyOnlyVideo')->name('destroy-only-video');
    Route::post('video/upload', 'VideoController@upload')->name('upload-video');

    /**
     * Series Video
     */
    Route::post('series/{id}/delete', 'SeriesController@destroyVideo')->name('series.destroy-video');
    Route::resource('series', 'SeriesController');
    Route::group([
        'prefix' => 'episode',
        'as'     => 'episode.',
    ], function () {
        Route::get('{seriesId}/create', 'EpisodeController@create')->name('create');
        Route::post('{seriesId}/store', 'EpisodeController@store')->name('store');
        Route::get('{seriesId}/edit/{id}', 'EpisodeController@edit')->name('edit');
        Route::patch('{seriesId}/update/{id}', 'EpisodeController@update')->name('update');
        Route::delete('{seriesId}/destroy/{id}', 'EpisodeController@destroy')->name('destroy');
        Route::get('{seriesId}/{id}', 'EpisodeController@show')->name('show');
        Route::post('video/{id}/delete', 'EpisodeController@destroyVideo')->name('destroy-video');
    });

    Route::resource('banner', 'BannerController');
    Route::resource('channel-agenda', 'ChannelAgendaController');

    /**
     * File Manage (Image)
     *
     * @todo video
     */
    Route::post('upload/files', 'FileUploadController@upload')->name('upload-file');
    Route::post('delete/files/{id}', 'FileUploadController@destroy')->name('destroy-file');

    /**
     * Notification
     */
    Route::get('notification/{id}/published', 'NotificationController@published')->name('notification.published');
    Route::resource('notification', 'NotificationController');
    //Route::get('send-notice', 'NoticeController@sendNotice');

    /**
     * Role & Permission
     */
    Route::resource('role', 'RoleController');
    Route::get('permission/{role_slug}', 'PermissionController@index')->name('permission.index');
    Route::post('permission/{role_id}', 'PermissionController@update')->name('permission.update');

    Route::resource('staff', 'StaffController');
    Route::resource('rtmp-stream', 'RtmpStreamController');
    Route::resource('info', 'InfoController')
        ->middleware('permission:info-manage');

    /**
     * CMS
     */
    Route::group(['prefix' => 'cms'], function () {
        Route::get('recommended/video', 'CmsController@individual_index')->name('cms.video-recommended');
        Route::post('recommended/video', 'CmsController@individual_store')->name('cms.video-recommended.store');

        Route::get('recommended/playlist', 'CmsController@playlist_index')->name('cms.playlist-recommended');
        Route::post('recommended/playlist', 'CmsController@playlist_store')->name('cms.playlist-recommended.store');

        Route::get('new-released/video', 'CmsController@new_released_video_index')->name('cms.new-released.video');
        Route::post('new-released/video', 'CmsController@new_released_video_store')
            ->name('cms.new-released.video.store');

        Route::get('series', 'CmsController@series_index')->name('cms.playlist');
        Route::post('series', 'CmsController@series_store')->name('cms.playlist.store');

        Route::get('cast', 'CmsController@cast_index')->name('cms.cast');
        Route::post('cast', 'CmsController@cast_store')->name('cms.cast.store');
    });

    Route::delete('comment/{id}', 'CommentController@destroy')->name('comment.destroy');

    /**
     * Pages
     */
    Route::get('about-us', 'AboutUsController@create')->name('about-us.create');
    Route::post('about-us', 'AboutUsController@save')->name('about-us.save');

    Route::get('contact-us', 'ContactUsController@create')->name('contact-us.create');
    Route::post('contact-us', 'ContactUsController@save')->name('contact-us.save');

    Route::get('faq', 'FaqController@create')->name('faq.create');
    Route::post('faq', 'FaqController@save')->name('faq.save');

    Route::get('support', 'SupportController@create')->name('support.create');
    Route::post('support', 'SupportController@save')->name('support.save');
});

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * Backend Auth
 */
Route::prefix(config('system.backend_url'))
    ->namespace('Auth\Admin')
    ->group(function () {
        Route::get('/login', 'LoginController@showLoginForm')->name('admin.login');
        Route::post('/login', 'LoginController@login')->name('admin.login.submit');
        Route::get('/logout', 'LoginController@logout')->name('admin.logout');
    });

/**
 * Frontend
 */
Auth::routes(['verify' => true]);

Route::get('test/login', function() {
    $user = \Arga\Auth\User::find(12);
    Auth::login($user);
});

Route::get('auth/{provider}', 'Auth\RegisterController@redirectToProvider')->name('auth.social.redirect');
Route::get('auth/{provider}/callback', 'Auth\RegisterController@handleProviderCallback')->name('auth.social.callback');

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

Route::get('/series/{series_id}', 'PagesController@series')->name('series.index');
Route::get('/series/{series_id}/video/{video_id}', 'PagesController@seriesDetail')->name('series.show');

Route::get('/series-by-category/{category_id}', 'PagesController@seriesByCategory');

Route::get('search', 'SearchController@showAll');

Route::get('/search-by-video', 'SearchController@byVideo');
Route::get('/search-by-series', 'SearchController@bySeries');
Route::get('/search-by-cast', 'SearchController@byCast');

Route::get('/live', 'HomeController@live')->name('live');

Route::get('/privacy-policy', 'HomeController@privacy')->name('privacy');
Route::get('/terms-and-conditions', 'HomeController@termsAndConditions')->name('terms.and.conditions');
Route::get('/about-us', 'HomeController@aboutUsPage')->name('about.us');
Route::get('/contact-us', 'HomeController@contactUsPage')->name('contact.us');
Route::get('/faq', 'HomeController@faqPage')->name('faq');
Route::get('/support-guide', 'HomeController@supportGuidePage')->name('support.guide');

Route::get('new-releases', 'PagesController@new_releases');
Route::get('series-recommended', 'PagesController@series_recommended');
Route::get('tv-shows', 'PagesController@tv_show');
Route::get('hot-videos', 'PagesController@hot_videos');
Route::get('hot-series', 'PagesController@hot_series');
Route::get('recommended-videos', 'PagesController@recommended_videos');
Route::get('recommended-castors', 'PagesController@recommended_castors');
Route::get('recommended-categories', 'PagesController@recommended_category');

Route::get('castors', 'PagesController@castors');
Route::get('castor/{id}', 'PagesController@castor');
Route::get('categories', 'PagesController@categories');

Route::get('agenda/{date}', 'PagesController@agenda');

Route::get('/comment/video/{video_id}', 'UserController@getComments');

Route::group([ 'middleware' => 'auth'], function() {
    Route::post('/comment/video/{video_id}', 'UserController@storeVideoComment');
    Route::delete('/comment/video/{video_id}', 'UserController@destroy');

    Route::post('video/{id}/favorite', 'UserController@syncVideoFavorite');
    Route::post('video/{id}/like', 'UserController@syncVideoLike');

    Route::get('/profile', 'UserController@profile');
    Route::get('/setting', 'UserController@setting');
    Route::post('/password/change','UserController@passwordChange')->name('user.password.change');
    Route::post('/account/edit_account_info','UserController@editProfile');
    Route::get('/notification/{id}', 'UserController@notification');
    Route::post('/notification-read', 'UserController@readNotification');
});

Route::get('/download-android-apk','DownloadAppController@android');

app/Http/Controllers/Api/AgendaController.php
<?php

namespace App\Http\Controllers\Api;

use App\Repositories\DataRepo;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AgendaController extends Controller
{
    protected $repo;

    public function __construct()
    {
        $this->repo = DataRepo::channel_agenda();
    }

    public function index()
    {
        return $this->repo->getByCurrentDate();
    }
}

app/Http/Controllers/Backend/AboutUsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Repositories\AboutUsRepository;
use Illuminate\Http\Request;

class AboutUsController extends BaseController
{
    protected $repo;

    public function __construct(AboutUsRepository $repo)
    {
        $this->repo = $repo;
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Exception
     */
    public function create()
    {
        $about = $this->repo->first();

        return $this->view('about_us.form', [
            'about' => $about,
        ]);
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function save(Request $request)
    {
        $this->repo->save($request->only('body'));

        return redirect()->route('backend.about-us.create')->with('success', 'Successfully!');
    }
}

app/Http/Controllers/Backend/BannerController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Repositories\DataRepo;
use App\Transformers\BannerTransformer;
use Arga\Auth\PermissionMiddlewareTrait;
use Illuminate\Http\Request;
use App\Models\Permission;

class BannerController extends BaseController
{
    use PermissionMiddlewareTrait;

    private $repo;

    public function __construct()
    {
        $this->actionMiddelware([
            'index'   => Permission::BANNER_INDEX,
            'create'  => Permission::BANNER_CREATE,
            'edit'    => Permission::BANNER_EDIT,
            'store'   => Permission::BANNER_CREATE,
            'update'  => Permission::BANNER_EDIT,
            'destroy' => Permission::BANNER_DELETE,
            'show'    => Permission::BANNER_SHOW,
        ]);

        $this->repo = DataRepo::banner();
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Exception
     */
    public function index()
    {
        $banners = $this->repo->paginate();

        $this->setupTitle(trans('banner.banner'));

        return $this->view('banner.index', [
            'banners' => $banners,
        ]);
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Exception
     */
    public function create()
    {
        $this->setupTitle(trans('banner.create_banner'));

        return $this->view('banner.create');
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Exception
     */
    public function edit($id)
    {
        $banner = $this->repo
            ->setTransformer(new BannerTransformer(true))
            ->find($id);

        $this->setupTitle(trans('banner.edit_banner'));

        $this->shareJS([
            'uploaded_image' => $banner['images'],
            'cover_image'    => $banner['cover_image'],
        ]);

        return $this->view('banner.edit', [
            'banner' => $banner,
        ]);
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Exception
     */
    public function show($id)
    {
        $banner = $this->repo
            ->setTransformer(new BannerTransformer(true))
            ->find($id);
        $this->setupTitle(trans('banner.banner_info'));

        return $this->view('banner.info', [
            'banner' => $banner,
        ]);
    }

    protected function setData(Request $request)
    {
        return $request->only([
            'title',
            'start_date',
            'end_date',
            'images',
            'cover_images',
            'url',
            'type',
            'type_id',
            'published_at',
        ]);
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $data = $this->setData($request);

        $this->repo->store($data);

        return redirect()->route('backend.banner.index')->with('success', 'Successfully!');
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, $id)
    {
        $data = $this->setData($request);
        $this->repo->update($data, $id);

        return redirect()->route('backend.banner.index')->with('success', 'Successfully!');
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\Routing\ResponseFactory|\Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy($id)
    {
        $this->repo->destroy($id);

        return ok();
    }
}

app/Http/Controllers/Backend/BaseController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller as Controller;
use Arga\Sidebar\Menu;
use Illuminate\Support\Facades\Route;

abstract class BaseController extends Controller
{
    protected function setupTitle($title)
    {
        view()->share('page_title', $title);

        return $this;
    }

    /**
     * @throws \Exception
     */
    protected function setupSidebar()
    {
        $confs = config('sidebar');
        Menu::$currentUrl = request()->fullUrl();

        foreach ($confs as $conf) {
            $sidebar[] = new Menu($conf, array_get($conf, 'parent'));
        }

        if (!isset($sidebar)) {
            throw new \Exception('Need Sidebar for template');
        }

        view()->share('sidebarMenus', $sidebar);
    }

    /**
     * @param array $data
     */
    protected function shareJS(array $data)
    {
        \JavaScript::put($data);
    }

    protected function setupBreadcrumb()
    {
        $breadcrumbs = $this->prepareBreadcrumbs();

        view()->share('breadcrumbs', $breadcrumbs);
    }

    /**
     * @return array
     */
    protected function prepareBreadcrumbs()
    {
        $current = [];
        $breadcrumbs = [];
        $confs = config('breadcrumbs');

        foreach ($confs as $k => $v) {
            if (isset($v['route']) && $v['route'] === Route::currentRouteName()) {
                $current = $v + [
                        'url' => 'javascript:void(0);',
                    ];
                $breadcrumbs[$k] = $current;
                break;
            }
        }

        do {
            $parentKey = array_get($current, 'parent');
            $parent = config('breadcrumbs.'.$parentKey);
            if ($parent) {
                $breadcrumbs[$parentKey] = $parent + [
                        'url' => route($parent['route']),
                    ];
                $current = $parent;
            }
        } while ($parent);

        $breadcrumbs = array_reverse($breadcrumbs);

        return $breadcrumbs;
    }

    /**
     * @param $view
     * @param array $data
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Exception
     */
    protected function view($view, array $data = [])
    {
        view()->share('auth_user', auth('admin')->user());

        $this->setupSidebar();

        $this->setupBreadcrumb();

        if (!str_contains($view, 'backend')) {
            $view = 'backend.'.$view;
        }

        $this->shareJsData();

        $layout = view('backend.layouts.app')->nest('content', $view, $data);

        return $layout;
    }

    protected function shareJsData()
    {
        $this->shareJS([
            'file_upload_url' => route('backend.upload-file'),
            'file_delete_url' => url('backend/delete/files'),
        ]);
    }
}

app/Http/Controllers/Backend/CommentController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Repositories\CommentRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CommentController extends Controller
{
    protected $repo;

    public function __construct(CommentRepository $repo)
    {
        $this->repo = $repo;
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\Routing\ResponseFactory|\Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy($id)
    {
        $this->repo->destroy($id);

        return ok();
    }
}

resources/views/backend/agenda/create.blade.php
@component('backend.components.full_box')
    @slot('titleTool')
        <a href="#" class="btn btn-outline-info m-btn m-btn--icon btn-lg m-btn--icon-only  m-btn--pill">
            <i class="la la-question"></i>
        </a>
    @endslot
    {{ Form::model(null,['route' => 'backend.channel-agenda.store', 'method' => 'POST', 'class' => 'm-form m-form--fit m-form--label-align-right']) }}
    @include('backend.agenda.form')
    {{ Form::close() }}
@endcomponent

resources/views/backend/agenda/edit.blade.php
@component('backend.components.full_box')
    @slot('titleTool')
        <a href="#" class="btn btn-outline-info m-btn m-btn--icon btn-lg m-btn--icon-only  m-btn--pill">
            <i class="la la-question"></i>
        </a>
    @endslot
    {{ Form::model($agenda,[
    'route' => ['backend.channel-agenda.update', $agenda['id']],
    'method' => 'PATCH',
    'class' => 'm-form m-form--fit m-form--label-align-right']) }}
    @include('backend.agenda.form')
    {{ Form::close() }}
@endcomponent

resources/views/backend/agenda/form.blade.php
<div class="m-portlet__body" style="padding-top: 0;">
    <agenda-form :preview="'{{ isset($agenda) ? true:false  }}'"></agenda-form>
</div>
<div class="m-portlet__foot m-portlet__foot--fit">
    <div class="m-form__actions">
        <button type="submit" class="btn btn-primary">
            <i class="la la-save"></i> Submit
        </button>
        <a href="{{ route('backend.channel-agenda.index') }}" class="btn btn-secondary">
            <i class="la la-rotate-right"></i>
            Cancel
        </a>
    </div>
</div>

@section('extraJs')
    <script src="{{ url('js/theme/bootstrap-datepicker.js') }}"></script>
    <script src="{{ url('js/theme/bootstrap-timepicker.js') }}"></script>
@append

resources/views/backend/agenda/index.blade.php
@component('backend.components.full_box')
    @slot('titleTool')
        <a href="{{ route('backend.channel-agenda.create') }}"
           class="btn btn-outline-primary m-btn m-btn--icon m-btn--outline-2x m-btn--pill m-btn--air">
            <span>
                <i class="la la-plus-circle"></i>
                <span>ADD</span>
            </span>
        </a>
    @endslot
    @foreach($agendas['data'] as $index=>$agenda)
        <div class="m-portlet">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            {{ $agenda['date']  }}
                        </h3>
                    </div>
                </div>
                <div class="m-portlet__head-tools">
                    <ul class="m-portlet__nav">
                        <li class="m-portlet__nav-item">
                            <a href="{{ route('backend.channel-agenda.edit', $agenda['id']) }}"
                               class="btn btn-outline-primary m-btn m-btn--icon">
                                <i class="la la-edit"></i> Edit
                            </a>
                            &nbsp;
                            <a href="#"
                               data-url="{{ route('backend.channel-agenda.destroy', $agenda['id']) }}"
                               class="delete_button btn btn-outline-danger m-btn m-btn--icon">
                                <i class="la la-trash"></i> Delete
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="m-portlet__body">
                <!--begin::Section-->
                <div class="m-section">
                    <div class="m-section-"></div>
                    <div class="m-section__content">
                        <table class="table table-bordered m-table m-table--border-brand m-table--head-bg-brand">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Time</th>
                                <th>Title</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($agenda['agendas'] as $index=>$data)
                                <tr>
                                    <th scope="row">{{ $index + 1 }}</th>
                                    <td>{{ $data['time'] }}</td>
                                    <td>{{ $data['title'] }}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                <!--end::Section-->
            </div>
            <!--end::Form-->
        </div>
    @endforeach
@endcomponent