routes/backend.php
<?php
/**
 * Created by PhpStorm.
 * User: naingminkhant
 * Date: 11/19/18
 * Time: 1:35 PM
 */

Route::get('/', 'DashboardController@index')->name('dashboard');

Route::group([
    'as' => 'backend.',
], function () {
    Route::resource('user', 'UserController');
    Route::resource('category', 'CategoryController');
    Route::resource('{category_id}/sub-category', 'SubCategoryController');

    Route::resource('director', 'DirectorController');
    Route::resource('cast', 'CastController');
    Route::resource('company', 'CompanyController');
    Route::resource('country', 'CountryController');

    /**
     * Individual Video
     */
    Route::post('video/{id}/delete', 'VideoController@destroyVideo')->name('destroy-video');
    Route::resource('video', 'VideoController');

    /**
     * Upload Video
     */
    Route::post('only-video/delete', 'VideoController@destroyOnlyVideo')->name('destroy-only-video');
    Route::post('video/upload', 'VideoController@upload')->name('upload-video');

    /**
     * Series Video
     */
    Route::post('series/{id}/delete', 'SeriesController@destroyVideo')->name('series.destroy-video');
    Route::resource('series', 'SeriesController');
    Route::group([
        'prefix' => 'episode',
        'as'     => 'episode.',
    ], function () {
        Route::get('{seriesId}/create', 'EpisodeController@create')->name('create');
        Route::post('{seriesId}/store', 'EpisodeController@store')->name('store');
        Route::get('{seriesId}/edit/{id}', 'EpisodeController@edit')->name('edit');
        Route::patch('{seriesId}/update/{id}', 'EpisodeController@update')->name('update');
        Route::delete('{seriesId}/destroy/{id}', 'EpisodeController@destroy')->name('destroy');
        Route::get('{seriesId}/{id}', 'EpisodeController@show')->name('show');
        Route::post('video/{id}/delete', 'EpisodeController@destroyVideo')->name('destroy-video');
    });

    Route::resource('banner', 'BannerController');
    Route::resource('channel-agenda', 'ChannelAgendaController');

    /**
     * File Manage (Image)
     *
     * @todo video
     */
    Route::post('upload/files', 'FileUploadController@upload')->name('upload-file');
    Route::post('delete/files/{id}', 'FileUploadController@destroy')->name('destroy-file');

    /**
     * Notification
     */
    Route::get('notification/{id}/published', 'NotificationController@published')->name('notification.published');
    Route::resource('notification', 'NotificationController');
    //Route::get('send-notice', 'NoticeController@sendNotice');

    /**
     * Role & Permission
     */
    Route::resource('role', 'RoleController');
    Route::get('permission/{role_slug}', 'PermissionController@index')->name('permission.index');
    Route::post('permission/{role_id}', 'PermissionController@update')->name('permission.update');

    Route::resource('staff', 'StaffController');
    Route::resource('rtmp-stream', 'RtmpStreamController');
    Route::resource('info', 'InfoController')
        ->middleware('permission:info-manage');

    /**
     * CMS
     */
    Route::group(['prefix' => 'cms'], function () {
        Route::get('recommended/video', 'CmsController@individual_index')->name('cms.video-recommended');
        Route::post('recommended/video', 'CmsController@individual_store')->name('cms.video-recommended.store');

        Route::get('recommended/playlist', 'CmsController@playlist_index')->name('cms.playlist-recommended');
        Route::post('recommended/playlist', 'CmsController@playlist_store')->name('cms.playlist-recommended.store');

        Route::get('new-released/video', 'CmsController@new_released_video_index')->name('cms.new-released.video');
        Route::post('new-released/video', 'CmsController@new_released_video_store')
            ->name('cms.new-released.video.store');

        Route::get('series', 'CmsController@series_index')->name('cms.playlist');
        Route::post('series', 'CmsController@series_store')->name('cms.playlist.store');

        Route::get('cast', 'CmsController@cast_index')->name('cms.cast');
        Route::post('cast', 'CmsController@cast_store')->name('cms.cast.store');
    });

    Route::delete('comment/{id}', 'CommentController@destroy')->name('comment.destroy');

    /**
     * Pages
     */
    Route::get('about-us', 'AboutUsController@create')->name('about-us.create');
    Route::post('about-us', 'AboutUsController@save')->name('about-us.save');

    Route::get('contact-us', 'ContactUsController@create')->name('contact-us.create');
    Route::post('contact-us', 'ContactUsController@save')->name('contact-us.save');

    Route::get('faq', 'FaqController@create')->name('faq.create');
    Route::post('faq', 'FaqController@save')->name('faq.save');

    Route::get('support', 'SupportController@create')->name('support.create');
    Route::post('support', 'SupportController@save')->name('support.save');
});

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * Backend Auth
 */
Route::prefix(config('system.backend_url'))
    ->namespace('Auth\Admin')
    ->group(function () {
        Route::get('/login', 'LoginController@showLoginForm')->name('admin.login');
        Route::post('/login', 'LoginController@login')->name('admin.login.submit');
        Route::get('/logout', 'LoginController@logout')->name('admin.logout');
    });

/**
 * Frontend
 */
Auth::routes(['verify' => true]);

Route::get('test/login', function() {
    $user = \Arga\Auth\User::find(12);
    Auth::login($user);
});

Route::get('auth/{provider}', 'Auth\RegisterController@redirectToProvider')->name('auth.social.redirect');
Route::get('auth/{provider}/callback', 'Auth\RegisterController@handleProviderCallback')->name('auth.social.callback');

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

Route::get('/series/{series_id}', 'PagesController@series')->name('series.index');
Route::get('/series/{series_id}/video/{video_id}', 'PagesController@seriesDetail')->name('series.show');

Route::get('/series-by-category/{category_id}', 'PagesController@seriesByCategory');

Route::get('search', 'SearchController@showAll');

Route::get('/search-by-video', 'SearchController@byVideo');
Route::get('/search-by-series', 'SearchController@bySeries');
Route::get('/search-by-cast', 'SearchController@byCast');

Route::get('/live', 'HomeController@live')->name('live');

Route::get('/privacy-policy', 'HomeController@privacy')->name('privacy');
Route::get('/terms-and-conditions', 'HomeController@termsAndConditions')->name('terms.and.conditions');
Route::get('/about-us', 'HomeController@aboutUsPage')->name('about.us');
Route::get('/contact-us', 'HomeController@contactUsPage')->name('contact.us');
Route::get('/faq', 'HomeController@faqPage')->name('faq');
Route::get('/support-guide', 'HomeController@supportGuidePage')->name('support.guide');

Route::get('new-releases', 'PagesController@new_releases');
Route::get('series-recommended', 'PagesController@series_recommended');
Route::get('tv-shows', 'PagesController@tv_show');
Route::get('hot-videos', 'PagesController@hot_videos');
Route::get('hot-series', 'PagesController@hot_series');
Route::get('recommended-videos', 'PagesController@recommended_videos');
Route::get('recommended-castors', 'PagesController@recommended_castors');
Route::get('recommended-categories', 'PagesController@recommended_category');

Route::get('castors', 'PagesController@castors');
Route::get('castor/{id}', 'PagesController@castor');
Route::get('categories', 'PagesController@categories');

Route::get('agenda/{date}', 'PagesController@agenda');

Route::get('/comment/video/{video_id}', 'UserController@getComments');

Route::group([ 'middleware' => 'auth'], function() {
    Route::post('/comment/video/{video_id}', 'UserController@storeVideoComment');
    Route::delete('/comment/video/{video_id}', 'UserController@destroy');

    Route::post('video/{id}/favorite', 'UserController@syncVideoFavorite');
    Route::post('video/{id}/like', 'UserController@syncVideoLike');

    Route::get('/profile', 'UserController@profile');
    Route::get('/setting', 'UserController@setting');
    Route::post('/password/change','UserController@passwordChange')->name('user.password.change');
    Route::post('/account/edit_account_info','UserController@editProfile');
    Route::get('/notification/{id}', 'UserController@notification');
    Route::post('/notification-read', 'UserController@readNotification');
});

Route::get('/download-android-apk','DownloadAppController@android');

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use App\Repositories\DataRepo;
use App\Http\Controllers\Controller;
use Arga\Auth\User;
use Arga\Storage\Cloudinary\CloudinaryClient;
use Illuminate\Http\Request;

class UserController extends Controller
{
    private $repo;

    private $image;

    public function __construct()
    {
        $this->repo = DataRepo::user();
        $this->image = app(CloudinaryClient::class);
    }

    public function me()
    {
        return $this->repo->getUser();
    }

    protected function setData(Request $request)
    {
        return $request->only([
            'name',
            'email',
            'current_password',
            'password',
            'password_confirmation',
        ]);
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Contracts\Routing\ResponseFactory|\Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request)
    {
        $data = $this->setData($request);
        $file = $request->file('image');
        $this->repo->updateFromApi($data, $file);

        return ok();
    }

    public function searchKeyword()
    {
        if ($this->authorizedUser() instanceof User) {
            return $this->authorizedUser()
                ->search_keywords()
                ->orderByDesc('created_at')
                ->limit(10)->get();
        }
    }

    public function destroySearchKeyword($id)
    {
        if ($this->authorizedUser() instanceof User) {
            $this->authorizedUser()
                ->search_keywords()
                ->where('search_keywords.id', $id)->delete();
            return ok();
        }
    }
}

app/Http/Controllers/Backend/AboutUsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Repositories\AboutUsRepository;
use Illuminate\Http\Request;

class AboutUsController extends BaseController
{
    protected $repo;

    public function __construct(AboutUsRepository $repo)
    {
        $this->repo = $repo;
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Exception
     */
    public function create()
    {
        $about = $this->repo->first();

        return $this->view('about_us.form', [
            'about' => $about,
        ]);
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function save(Request $request)
    {
        $this->repo->save($request->only('body'));

        return redirect()->route('backend.about-us.create')->with('success', 'Successfully!');
    }
}

app/Http/Controllers/Backend/BannerController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Repositories\DataRepo;
use App\Transformers\BannerTransformer;
use Arga\Auth\PermissionMiddlewareTrait;
use Illuminate\Http\Request;
use App\Models\Permission;

class BannerController extends BaseController
{
    use PermissionMiddlewareTrait;

    private $repo;

    public function __construct()
    {
        $this->actionMiddelware([
            'index'   => Permission::BANNER_INDEX,
            'create'  => Permission::BANNER_CREATE,
            'edit'    => Permission::BANNER_EDIT,
            'store'   => Permission::BANNER_CREATE,
            'update'  => Permission::BANNER_EDIT,
            'destroy' => Permission::BANNER_DELETE,
            'show'    => Permission::BANNER_SHOW,
        ]);

        $this->repo = DataRepo::banner();
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Exception
     */
    public function index()
    {
        $banners = $this->repo->paginate();

        $this->setupTitle(trans('banner.banner'));

        return $this->view('banner.index', [
            'banners' => $banners,
        ]);
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Exception
     */
    public function create()
    {
        $this->setupTitle(trans('banner.create_banner'));

        return $this->view('banner.create');
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Exception
     */
    public function edit($id)
    {
        $banner = $this->repo
            ->setTransformer(new BannerTransformer(true))
            ->find($id);

        $this->setupTitle(trans('banner.edit_banner'));

        $this->shareJS([
            'uploaded_image' => $banner['images'],
            'cover_image'    => $banner['cover_image'],
        ]);

        return $this->view('banner.edit', [
            'banner' => $banner,
        ]);
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Exception
     */
    public function show($id)
    {
        $banner = $this->repo
            ->setTransformer(new BannerTransformer(true))
            ->find($id);
        $this->setupTitle(trans('banner.banner_info'));

        return $this->view('banner.info', [
            'banner' => $banner,
        ]);
    }

    protected function setData(Request $request)
    {
        return $request->only([
            'title',
            'start_date',
            'end_date',
            'images',
            'cover_images',
            'url',
            'type',
            'type_id',
            'published_at',
        ]);
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $data = $this->setData($request);

        $this->repo->store($data);

        return redirect()->route('backend.banner.index')->with('success', 'Successfully!');
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, $id)
    {
        $data = $this->setData($request);
        $this->repo->update($data, $id);

        return redirect()->route('backend.banner.index')->with('success', 'Successfully!');
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\Routing\ResponseFactory|\Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy($id)
    {
        $this->repo->destroy($id);

        return ok();
    }
}

app/Http/Controllers/Backend/CommentController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Repositories\CommentRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CommentController extends Controller
{
    protected $repo;

    public function __construct(CommentRepository $repo)
    {
        $this->repo = $repo;
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\Routing\ResponseFactory|\Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy($id)
    {
        $this->repo->destroy($id);

        return ok();
    }
}

app/Http/Controllers/Backend/ContactUsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Repositories\ContactUsRepository;
use Illuminate\Http\Request;

class ContactUsController extends BaseController
{
    protected $repo;

    public function __construct(ContactUsRepository $repo)
    {
        $this->repo = $repo;
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Exception
     */
    public function create()
    {
        $contact = $this->repo->first();

        return $this->view('contact_us.form', [
            'contact' => $contact,
        ]);
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function save(Request $request)
    {
        $this->repo->save($request->only('body'));

        return redirect()->route('backend.contact-us.create')->with('success', 'Successfully!');
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

class DashboardController extends BaseController
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Exception
     */
    public function index()
    {
        return $this->view('dashboard');
    }
}

resources/views/backend/user/create.blade.php
@component('backend.components.full_box')
    @slot('titleTool')
        <a href="#" class="btn btn-outline-info m-btn m-btn--icon btn-lg m-btn--icon-only  m-btn--pill">
            <i class="la la-question"></i>
        </a>
    @endslot
    {{ Form::model(null,['route' => 'backend.user.store', 'method' => 'POST', 'class' => 'm-form m-form--fit m-form--label-align-right']) }}
    @include('backend.user.form')
    {{ Form::close() }}
@endcomponent

resources/views/backend/user/edit.blade.php
@component('backend.components.full_box')
    @slot('titleTool')
        <a href="#" class="btn btn-outline-info m-btn m-btn--icon btn-lg m-btn--icon-only  m-btn--pill">
            <i class="la la-question"></i>
        </a>
    @endslot
    {{ Form::model($user,[
    'route' => ['backend.user.update', $user['id']],
    'method' => 'PATCH',
    'class' => 'm-form m-form--fit m-form--label-align-right']) }}
    @include('backend.user.form')
    {{ Form::close() }}
@endcomponent

resources/views/backend/user/form.blade.php
<div class="m-portlet__body">
    <div class="form-group m-form__group row">
        <label class="col-form-label col-lg-2 col-sm-12">Name :</label>
        <div class="col-lg-6 col-md-10 col-sm-12">
            {{ Form::input('text','name', null, ['class' => 'form-control m-input', 'placeholder' => 'Full Name']) }}
        </div>
    </div>
    <div class="form-group m-form__group row">
        <label class="col-form-label col-lg-2 col-sm-12">Email :</label>
        <div class="col-lg-6 col-md-10 col-sm-12">
            {{ Form::input('email','email', null, ['class' => 'form-control m-input', 'placeholder' => 'Email']) }}
        </div>
    </div>
    <div class="form-group m-form__group row">
        <label class="col-form-label col-lg-2 col-sm-12">Password :</label>
        <div class="col-lg-6 col-md-10 col-sm-12">
            {{ Form::input('password','password', null, ['class' => 'form-control m-input', 'placeholder' => 'Password']) }}
        </div>
    </div>
    <div class="form-group m-form__group row">
        <label class="col-form-label col-lg-2 col-sm-12">Confirm Password :</label>
        <div class="col-lg-6 col-md-10 col-sm-12">
            {{ Form::input('password','password_confirmation', null, ['class' => 'form-control m-input', 'placeholder' => 'Confirm Password']) }}
        </div>
    </div>
    <div class="form-group m-form__group row">
        <label class="col-form-label col-lg-2 col-sm-12"></label>
        <div class="col-lg-6 col-md-10 col-sm-12">
            <div class="m-checkbox-inline">
                <label class="m-checkbox">
                    {!! Form::checkbox('ban', null, isset($user['banned_at']) ? $user['banned_at']:false) !!}
                    <label>Ban</label>
                    <span></span>
                </label>
            </div>
        </div>
    </div>
</div>
<div class="m-portlet__foot m-portlet__foot--fit">
    <div class="m-form__actions">
        <button type="submit" class="btn btn-primary">
            <i class="la la-save"></i> Submit
        </button>
        <a href="{{ route('backend.user.index') }}" class="btn btn-secondary">
            <i class="la la-rotate-right"></i>
            Cancel
        </a>
    </div>
</div>

@section('extraJs')
    <script src="{{ url('js/theme/select2.js') }}"></script>
@append

resources/views/backend/user/index.blade.php
@component('backend.components.full_box')
    @slot('titleTool')
        <a href="{{ route('backend.user.create') }}"
           class="btn btn-outline-primary m-btn m-btn--icon m-btn--outline-2x m-btn--pill m-btn--air">
            <span>
                <i class="la la-plus-circle"></i>
                <span>ADD</span>
            </span>
        </a>
    @endslot
    <div class="form-group">
        @include('backend.user.search')
    </div>
    @component('backend.components.table',[
        'data'      => $users,
        'configs'   => config('tables.user')
    ])
    @endcomponent
@endcomponent

resources/views/backend/user/info.blade.php
@component('backend.components.full_box')
    @slot('title')

    @endslot
    <div class="col-xl-8 offset-xl-2">
        <div class="m-form__section m-form__section--first">
            <div class="m-form__heading">
                <h3 class="m-form__heading-title">Basic Details</h3>
            </div>
            <div class="form-group m-form__group row">
                <label class="col-xl-3 col-lg-3 col-form-label">Name:</label>
                <div class="col-xl-9 col-lg-9">
                    <input type="text" name="name" class="form-control m-input" placeholder=""
                           value="{{ $user['name'] }}" readonly>
                </div>
            </div>
            <div class="form-group m-form__group row">
                <label class="col-xl-3 col-lg-3 col-form-label">Email:</label>
                <div class="col-xl-9 col-lg-9">
                    <input type="email" name="email" class="form-control m-input" placeholder=""
                           value="{{ $user['email'] }}" readonly>
                </div>
            </div>
        </div>
        <div class="m-separator m-separator--dashed m-separator--lg"></div>
        <div class="m-form__section m-form__section--first">
            <div class="m-form__heading">
                <h3 class="m-form__heading-title">Security Details</h3>
            </div>
            <div class="form-group m-form__group row">
                <label class="col-xl-3 col-lg-3 col-form-label">Banned At:</label>
                <div class="col-xl-9 col-lg-9">
                    <input type="text" name="name" class="form-control m-input" placeholder=""
                           value="{{ $user['banned_at'] }}" readonly>
                </div>
            </div>
        </div>
    </div>
@endcomponent

resources/views/backend/user/search.blade.php
<form class="m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed">
    <div class="m-portlet__body">
        <div class="form-group m-form__group row" style="background-color: #fbfafa;">
            <div class="col-lg-4">
                <input type="text" name="q" class="form-control m-input" placeholder="enter keyword (eg., name)" value="{{ request()->q }}">
            </div>
            <div class="col-lg-4">
                <button class="btn btn-primary">Search</button>
                <a href="{{route('backend.user.index')}}" class="btn btn-danger">Reset</a>
            </div>
        </div>
    </div>
</form>